/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    'product-categories': ProductCategory;
    applications: Application;
    services: Service;
    pages: Page;
    posts: Post;
    updates: Update;
    documents: Document;
    media: Media;
    faqs: Faq;
    team: Team;
    testimonials: Testimonial;
    certifications: Certification;
    inquiries: Inquiry;
    subscribers: Subscriber;
    customers: Customer;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    updates: UpdatesSelect<false> | UpdatesSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * One entry per product family (e.g. "SP Agarose"). Add grades, specifications, pack sizes and documents.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * e.g. "Strong cation exchanger" or "Transition metal removal evaluation kit"
   */
  subtitle?: string | null;
  category: number | ProductCategory;
  availability: 'available' | 'made-to-order' | 'in-development';
  /**
   * Two to three sentences. Shown on cards, search results and given to AI assistants.
   */
  summary: string;
  /**
   * Full product overview.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  keyFeatures?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Main product image.
   */
  image?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  chemistry?: {
    ligand?: string | null;
    matrix?: string | null;
    /**
     * e.g. Strong cation exchanger, IMAC, HIC
     */
    functionalType?: string | null;
  };
  /**
   * Particle-size grades this product ships in. Each grade gets its own column on the comparison table.
   */
  grades?:
    | {
        grade: 'faster' | 'fast-flow' | 'precise' | 'hr';
        /**
         * Display name, e.g. "SP Agarose Fast Flow"
         */
        label?: string | null;
        /**
         * e.g. 45–165 µm
         */
        particleSizeRange?: string | null;
        /**
         * e.g. ~90 µm
         */
        d50?: string | null;
        /**
         * e.g. 700 cm/h
         */
        maxFlowVelocity?: string | null;
        /**
         * e.g. ≥100 mg lysozyme/mL
         */
        dynamicBindingCapacity?: string | null;
        /**
         * e.g. 250–450 cm/h, 0.1 MPa, 15 cm bed height
         */
        pressureFlow?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shared parameters (ionic capacity, pH stability, chemical stability, storage…). Optionally add the typical market specification for benchmarking.
   */
  specs?:
    | {
        parameter: string;
        value: string;
        marketSpec?: string | null;
        id?: string | null;
      }[]
    | null;
  applications?: (number | Application)[] | null;
  useCases?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  packSizes?:
    | {
        /**
         * e.g. 100 mL, 1 L, 10 L
         */
        size: string;
        catalogNumber?: string | null;
        grade?: ('faster' | 'fast-flow' | 'precise' | 'hr') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown on the product page next to the quote button.
   */
  leadTime?: string | null;
  bulkAvailable?: boolean | null;
  /**
   * Datasheets and other PDFs for this product.
   */
  documents?: (number | Document)[] | null;
  relatedProducts?: (number | Product)[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Show on the homepage.
   */
  featured?: boolean | null;
  /**
   * Sort order within its category.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Chromatography modes and product families. Order controls the sequence on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Used in tight spaces, e.g. "IEX", "IMAC".
   */
  shortName?: string | null;
  /**
   * One line under the category name, e.g. "Capture, intermediate and polishing".
   */
  tagline?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  icon?:
    ('ion-exchange' | 'affinity' | 'sec' | 'hic' | 'mixed-mode' | 'activated' | 'column' | 'kit' | 'magnetic') | null;
  order?: number | null;
  image?: (number | null) | Media;
  /**
   * The purification mode this category belongs to; used for filters and structured data.
   */
  mode?:
    | ('ion-exchange' | 'affinity' | 'size-exclusion' | 'hydrophobic-interaction' | 'mixed-mode' | 'formats' | 'kits')
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for accessibility and search engines.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Industries and workflows Protpure serves (biologics, vaccines, diagnostics…). Each gets a landing page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  summary: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  /**
   * Short bullets, e.g. "Recombinant proteins", "Monoclonal antibodies".
   */
  workflows?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  recommendedProducts?: (number | Product)[] | null;
  order?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * PDF downloads: datasheets, brochures, case studies. Link them to products so they appear on product pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  type:
    | 'datasheet'
    | 'brochure'
    | 'catalog'
    | 'case-study'
    | 'application-note'
    | 'performance-data'
    | 'poster'
    | 'presentation'
    | 'certificate'
    | 'other';
  documentDate?: string | null;
  /**
   * e.g. Rev 1.0
   */
  revision?: string | null;
  /**
   * One or two sentences shown in the resource library and used by AI assistants.
   */
  summary?: string | null;
  products?: (number | Product)[] | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Downstream bioprocessing services (column packing, resin screening, method development, purification service).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  tagline?: string | null;
  summary: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  deliverables?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  idealFor?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Build pages from blocks. Special slugs: "home" is the homepage; "products", "applications", "services", "resources", "blog", "updates", "contact", "request-quote", "faq" provide the intro for those listing pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero?: {
    style?: ('standard' | 'compact' | 'none') | null;
    eyebrow?: string | null;
    /**
     * Defaults to the page title.
     */
    heading?: string | null;
    /**
     * Optional: words from the heading to colour in the accent shade.
     */
    highlight?: string | null;
    text?: string | null;
    image?: (number | null) | Media;
    /**
     * Medallion on the photo, e.g. "BPG 200".
     */
    imageMarker?: string | null;
    /**
     * Small line in the medallion, e.g. "Client deployment".
     */
    imageMarkerNote?: string | null;
    /**
     * Caption under the photo, e.g. "Ni-NTA Agarose in a process column".
     */
    imageCaption?: string | null;
    /**
     * Right-hand caption, e.g. "At a client site".
     */
    imageCaptionNote?: string | null;
    links?:
      | {
          link: {
            type?: ('internal' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'products';
                  value: number | Product;
                } | null)
              | ({
                  relationTo: 'product-categories';
                  value: number | ProductCategory;
                } | null)
              | ({
                  relationTo: 'applications';
                  value: number | Application;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            appearance?: ('primary' | 'secondary' | 'ghost') | null;
          };
          id?: string | null;
        }[]
      | null;
    /**
     * Small pills under the buttons, e.g. "BioProcess grade".
     */
    badges?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  layout?:
    | (
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            width?: ('narrow' | 'wide') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            source?: ('settings' | 'custom') | null;
            /**
             * Short statements, e.g. "CoA with every lot". Claims only, no invented certifications.
             */
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'trustStrip';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  /**
                   * The numeral, e.g. 600
                   */
                  value: string;
                  /**
                   * Shown small next to the numeral, e.g. L / month
                   */
                  unit?: string | null;
                  label: string;
                  note?: string | null;
                  id?: string | null;
                }[]
              | null;
            style?: ('light' | 'dark') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            /**
             * Small label above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            intro?: string | null;
            columns?: ('2' | '3' | '4') | null;
            items?:
              | {
                  icon?:
                    | (
                        | 'purity'
                        | 'reproducible'
                        | 'flow'
                        | 'delivery'
                        | 'factory'
                        | 'cost'
                        | 'globe'
                        | 'shield'
                        | 'support'
                        | 'scale'
                        | 'beaker'
                        | 'document'
                        | 'microscope'
                        | 'chart'
                        | 'handshake'
                        | 'clock'
                      )
                    | null;
                  title: string;
                  text: string;
                  link?: {
                    type?: ('internal' | 'custom') | null;
                    newTab?: boolean | null;
                    reference?:
                      | ({
                          relationTo: 'pages';
                          value: number | Page;
                        } | null)
                      | ({
                          relationTo: 'products';
                          value: number | Product;
                        } | null)
                      | ({
                          relationTo: 'product-categories';
                          value: number | ProductCategory;
                        } | null)
                      | ({
                          relationTo: 'applications';
                          value: number | Application;
                        } | null)
                      | ({
                          relationTo: 'posts';
                          value: number | Post;
                        } | null);
                    url?: string | null;
                    label?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            /**
             * Show 01, 02, 03… instead of icons.
             */
            numbered?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            /**
             * Small label above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            links?:
              | {
                  link: {
                    type?: ('internal' | 'custom') | null;
                    newTab?: boolean | null;
                    reference?:
                      | ({
                          relationTo: 'pages';
                          value: number | Page;
                        } | null)
                      | ({
                          relationTo: 'products';
                          value: number | Product;
                        } | null)
                      | ({
                          relationTo: 'product-categories';
                          value: number | ProductCategory;
                        } | null)
                      | ({
                          relationTo: 'applications';
                          value: number | Application;
                        } | null)
                      | ({
                          relationTo: 'posts';
                          value: number | Post;
                        } | null);
                    url?: string | null;
                    label: string;
                    appearance?: ('primary' | 'secondary' | 'ghost') | null;
                  };
                  id?: string | null;
                }[]
              | null;
            image?: (number | null) | Media;
            /**
             * Caption line under the image, e.g. "Process evaluation in the Protpure lab".
             */
            imageCaption?: string | null;
            /**
             * Right-hand side of the caption, e.g. "Anand, Gujarat".
             */
            imageCaptionNote?: string | null;
            imagePosition?: ('right' | 'left') | null;
            /**
             * Optional smaller image under the main one (e.g. facility exterior). Until it is uploaded, editors see a dashed slot in preview; visitors see only the text.
             */
            secondImage?: (number | null) | Media;
            /**
             * Text beside the second image.
             */
            secondImageText?: string | null;
            /**
             * Optional quotation shown after the text (attribution comes from a following Team grid in "spread" layout).
             */
            quote?: string | null;
            background?: ('light' | 'recessed') | null;
            /**
             * Key/value list shown under the text, e.g. Location → Anand, Gujarat.
             */
            facts?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'twoColumn';
          }
        | {
            /**
             * Small label above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            intro?: string | null;
            columnA: string;
            columnB: string;
            rows?:
              | {
                  parameter: string;
                  a: string;
                  b: string;
                  id?: string | null;
                }[]
              | null;
            note?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'comparisonTable';
          }
        | {
            /**
             * Small label above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            intro?: string | null;
            grades?:
              | {
                  /**
                   * e.g. Agarose Precise
                   */
                  name: string;
                  /**
                   * Application label, e.g. Industrial capture
                   */
                  badge?: string | null;
                  /**
                   * e.g. ~60 µm
                   */
                  d50?: string | null;
                  /**
                   * e.g. 25–110 µm
                   */
                  sizeRange?: string | null;
                  /**
                   * e.g. up to 380 cm/h
                   */
                  maxFlow?: string | null;
                  /**
                   * e.g. < 0.12 MPa
                   */
                  pressure?: string | null;
                  text?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Footnote under the plot, e.g. "Bars show size range; dots show d50V. Platform values…"
             */
            note?: string | null;
            link?: {
              type?: ('internal' | 'custom') | null;
              newTab?: boolean | null;
              reference?:
                | ({
                    relationTo: 'pages';
                    value: number | Page;
                  } | null)
                | ({
                    relationTo: 'products';
                    value: number | Product;
                  } | null)
                | ({
                    relationTo: 'product-categories';
                    value: number | ProductCategory;
                  } | null)
                | ({
                    relationTo: 'applications';
                    value: number | Application;
                  } | null)
                | ({
                    relationTo: 'posts';
                    value: number | Post;
                  } | null);
              url?: string | null;
              label?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'gradesPlatform';
          }
        | {
            /**
             * Small label above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            intro?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'resinSelector';
          }
        | {
            /**
             * Small label above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            intro?: string | null;
            /**
             * Leave empty to show every category. Pick the main chromatography modes and mention the rest in the footnote.
             */
            categories?: (number | ProductCategory)[] | null;
            /**
             * Line under the grid, e.g. "Also available: pre-packed columns, magnetic beads & evaluation kits."
             */
            footnote?: string | null;
            /**
             * Catalogue link label. Defaults to "All N products".
             */
            linkLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productCategories';
          }
        | {
            /**
             * Small label above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            intro?: string | null;
            /**
             * Leave empty to show products marked "featured".
             */
            products?: (number | Product)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredProducts';
          }
        | {
            /**
             * Small label above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            intro?: string | null;
            layout?: ('cards' | 'list') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'applicationsGrid';
          }
        | {
            /**
             * Small label above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            intro?: string | null;
            layout?: ('cards' | 'row') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'servicesGrid';
          }
        | {
            /**
             * Small label above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            intro?: string | null;
            /**
             * Leave empty for all types.
             */
            types?:
              | (
                  | 'datasheet'
                  | 'brochure'
                  | 'catalog'
                  | 'case-study'
                  | 'application-note'
                  | 'performance-data'
                  | 'poster'
                  | 'presentation'
                  | 'certificate'
                  | 'other'
                )[]
              | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'documentList';
          }
        | {
            /**
             * Small label above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'latestPosts';
          }
        | {
            /**
             * Small label above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            intro?: string | null;
            limit?: number | null;
            /**
             * Optional: show only updates of this kind (set on each LinkedIn update).
             */
            kind?: ('product-launch' | 'data' | 'milestone' | 'services' | 'perspective') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'linkedInFeed';
          }
        | {
            /**
             * Small label above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            /**
             * Leave empty to show all.
             */
            items?: (number | Testimonial)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            /**
             * Small label above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            intro?: string | null;
            /**
             * Leave empty to show everyone.
             */
            members?: (number | Team)[] | null;
            layout?: ('grid' | 'spread') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'teamGrid';
          }
        | {
            /**
             * Small label above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            items?:
              | {
                  /**
                   * e.g. May 2023
                   */
                  date: string;
                  title: string;
                  text?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
        | {
            /**
             * Small label above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            intro?: string | null;
            category?: ('all' | 'products' | 'ordering' | 'shipping' | 'quality' | 'technical') | null;
            /**
             * Optional: pick specific questions instead of a category.
             */
            faqs?: (number | Faq)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqBlock';
          }
        | {
            image: number | Media;
            caption?: string | null;
            size?: ('wide' | 'narrow' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaBlock';
          }
        | {
            form: 'quote' | 'contact' | 'partnership' | 'newsletter';
            heading?: string | null;
            intro?: string | null;
            /**
             * Optional text shown next to the form (what happens next, response times…).
             */
            sidebar?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'formBlock';
          }
        | {
            /**
             * Small label above the heading.
             */
            eyebrow?: string | null;
            heading: string;
            /**
             * Blank lines start new paragraphs.
             */
            text?: string | null;
            /**
             * Short emphasised line after the text, e.g. the paid-evaluation credit policy.
             */
            note?: string | null;
            links?:
              | {
                  link: {
                    type?: ('internal' | 'custom') | null;
                    newTab?: boolean | null;
                    reference?:
                      | ({
                          relationTo: 'pages';
                          value: number | Page;
                        } | null)
                      | ({
                          relationTo: 'products';
                          value: number | Product;
                        } | null)
                      | ({
                          relationTo: 'product-categories';
                          value: number | ProductCategory;
                        } | null)
                      | ({
                          relationTo: 'applications';
                          value: number | Application;
                        } | null)
                      | ({
                          relationTo: 'posts';
                          value: number | Post;
                        } | null);
                    url?: string | null;
                    label: string;
                    appearance?: ('primary' | 'secondary' | 'ghost') | null;
                  };
                  id?: string | null;
                }[]
              | null;
            style?: ('dark' | 'accent' | 'light' | 'evaluation') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            /**
             * Small label above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            source?: ('all' | 'picked') | null;
            /**
             * Only customers with a logo and "Show logo" ticked are rendered.
             */
            customers?: (number | Customer)[] | null;
            /**
             * Shown instead of logos while none can be published. Defaults to Site settings → Proof points → Customers statement.
             */
            fallbackStatement?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logoWall';
          }
        | {
            heading?: string | null;
            /**
             * Leave empty for all kinds.
             */
            kinds?: ('quality-system' | 'product-claim' | 'regulatory' | 'membership' | 'award')[] | null;
            limit?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'certificationsStrip';
          }
        | {
            /**
             * Small label above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            /**
             * Facility, lab and team photos. The block is hidden until at least one photo is added.
             */
            items?:
              | {
                  image: number | Media;
                  /**
                   * Small tag, e.g. "Production" or "QC lab".
                   */
                  label?: string | null;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            layout?: ('grid' | 'strip' | 'spread') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            /**
             * Small label above the heading.
             */
            eyebrow?: string | null;
            heading?: string | null;
            /**
             * Leave empty to list publications of every team member marked "featured".
             */
            member?: (number | null) | Team;
            id?: string | null;
            blockName?: string | null;
            blockType: 'publications';
          }
        | {
            /**
             * Include the customers statement from Site settings → Proof points.
             */
            showStatement?: boolean | null;
            style?: ('light' | 'dark') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'proofBar';
          }
      )[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Shown in listings, social previews and the RSS feed.
   */
  excerpt: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  tags?: ('science' | 'application-note' | 'case-study' | 'news' | 'events' | 'india')[] | null;
  relatedProducts?: (number | Product)[] | null;
  author?: (number | null) | Team;
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  role: string;
  /**
   * One-line bio for compact layouts, e.g. "Materials scientist · bead synthesis and ligand chemistry".
   */
  tagline?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Square portrait. Until one is uploaded the site shows the member’s initials.
   */
  photo?: (number | null) | Media;
  /**
   * Degrees and titles, e.g. "Ph.D. (Physics)". Shown under the name and given to AI assistants.
   */
  credentials?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Short phrases, e.g. "ligand coupling".
   */
  expertise?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Peer-reviewed papers, patents or theses. Verify before publishing: title, journal, year and link must match the published record.
   */
  publications?:
    | {
        title: string;
        /**
         * Journal or publisher, with volume/pages if known.
         */
        journal?: string | null;
        year?: number | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  linkedinUrl?: string | null;
  email?: string | null;
  /**
   * Featured members supply the publications block and the founder entry in structured data.
   */
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer quotes and logos. Only publish with written permission from the customer — tick "Consent on file" once you have it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  person?: string | null;
  role?: string | null;
  organization: string;
  country?: string | null;
  /**
   * How the customer uses Protpure resins. Shown as a small label on the quote.
   */
  context?: ('evaluation' | 'production' | 'research' | 'distributor') | null;
  logo?: (number | null) | Media;
  products?: (number | Product)[] | null;
  /**
   * Only publish with written permission. Internal note — not shown on the site.
   */
  consentOnFile?: boolean | null;
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category: 'products' | 'ordering' | 'shipping' | 'quality' | 'technical';
  order?: number | null;
  /**
   * Show this FAQ on these product pages.
   */
  products?: (number | Product)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer references for the logo wall. Only tick "Show logo" with the customer’s permission.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  name: string;
  /**
   * Transparent PNG or SVG, ideally wider than tall.
   */
  logo?: (number | null) | Media;
  website?: string | null;
  sector?: ('biopharma' | 'vaccines' | 'diagnostics' | 'cdmo' | 'research' | 'distributor') | null;
  country?: string | null;
  /**
   * How to refer to this customer without naming them, e.g. "Indian vaccine manufacturer". Used when the logo cannot be shown.
   */
  anonymisedLabel?: string | null;
  /**
   * Requires the customer’s permission and an uploaded logo.
   */
  showLogo?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Paste the URL of a public LinkedIn post. The site embeds it automatically and shows your summary as a fallback for readers without LinkedIn. Drafts are hidden from the site until you publish.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "updates".
 */
export interface Update {
  id: number;
  /**
   * Short headline for the update.
   */
  title: string;
  /**
   * Required to publish. Drafts can be saved without it.
   */
  url: string;
  /**
   * Auto-filled from the URL. Only edit if the embed does not load.
   */
  urn?: string | null;
  /**
   * Two or three sentences. Shown as the card text and used by AI assistants.
   */
  summary: string;
  /**
   * Optional: the post image, so the card looks good without loading LinkedIn.
   */
  image?: (number | null) | Media;
  relatedProducts?: (number | Product)[] | null;
  /**
   * Lets page blocks show only one type of update, e.g. product launches.
   */
  kind?: ('product-launch' | 'data' | 'milestone' | 'services' | 'perspective') | null;
  publishedAt: string;
  /**
   * Pinned updates are listed first.
   */
  pinned?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Certifications, registrations and quality claims shown in the certifications strip and given to AI assistants. Upload the certificate PDF under Content → Documents and link it here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: number;
  /**
   * e.g. "ISO 9001:2015" or "Certificate of analysis with every lot".
   */
  name: string;
  kind: 'quality-system' | 'product-claim' | 'regulatory' | 'membership' | 'award';
  /**
   * Certifying body or authority. Leave empty for Protpure’s own claims.
   */
  issuer?: string | null;
  /**
   * One sentence explaining what this means for a buyer.
   */
  statement?: string | null;
  /**
   * Expiry date of the certificate, if any.
   */
  validUntil?: string | null;
  /**
   * The certificate PDF (Content → Documents).
   */
  document?: (number | null) | Document;
  /**
   * Badge or issuer logo (optional).
   */
  logo?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Quote and contact requests from the website (RFQ basket), the public API and AI assistants. Update the status as you work them.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  subjectLine?: string | null;
  type: 'quote' | 'evaluation' | 'technical' | 'partnership' | 'contact';
  status: 'new' | 'in-progress' | 'quoted' | 'won' | 'closed';
  name: string;
  email: string;
  organization?: string | null;
  jobTitle?: string | null;
  phone?: string | null;
  country?: string | null;
  /**
   * Line items from the RFQ basket (or from an API / MCP caller). Sample kits are paid and credited against the first bulk order.
   */
  items?:
    | {
        product?: (number | null) | Product;
        /**
         * Name at the time of the request (kept even if the product is renamed or removed).
         */
        productName: string;
        grade?: ('faster' | 'fast-flow' | 'precise' | 'hr') | null;
        /**
         * e.g. 1 L, 5 mL, Bulk (custom)
         */
        packSize?: string | null;
        catalogNumber?: string | null;
        quantity?: number | null;
        purpose?: ('sample-kit' | 'evaluation' | 'production' | 'other') | null;
        /**
         * Line note from the requester, e.g. column geometry or target volume.
         */
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * All products referenced by this inquiry (filled automatically from the items; also used by legacy API callers).
   */
  products?: (number | Product)[] | null;
  /**
   * Free text as entered by the requester or an AI assistant, e.g. "SP Agarose Precise, 2 × 1 L".
   */
  requestedItems?: string | null;
  /**
   * What they are purifying / their process.
   */
  application?: string | null;
  message?: string | null;
  /**
   * Captured automatically.
   */
  meta?: {
    source?: ('website' | 'mcp' | 'api' | 'manual') | null;
    pageUrl?: string | null;
    userAgent?: string | null;
    ip?: string | null;
    consent?: boolean | null;
  };
  /**
   * Only visible to your team.
   */
  internalNotes?: string | null;
  assignedTo?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Editors manage content. Admins also manage users and site settings.
   */
  roles: ('admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Double opt-in list. Export confirmed subscribers to your email tool when sending a newsletter.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  name?: string | null;
  organization?: string | null;
  status: 'pending' | 'confirmed' | 'unsubscribed';
  token?: string | null;
  confirmedAt?: string | null;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'updates';
        value: number | Update;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'certifications';
        value: number | Certification;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  subtitle?: T;
  category?: T;
  availability?: T;
  summary?: T;
  description?: T;
  keyFeatures?:
    | T
    | {
        text?: T;
        id?: T;
      };
  image?: T;
  gallery?: T;
  chemistry?:
    | T
    | {
        ligand?: T;
        matrix?: T;
        functionalType?: T;
      };
  grades?:
    | T
    | {
        grade?: T;
        label?: T;
        particleSizeRange?: T;
        d50?: T;
        maxFlowVelocity?: T;
        dynamicBindingCapacity?: T;
        pressureFlow?: T;
        id?: T;
      };
  specs?:
    | T
    | {
        parameter?: T;
        value?: T;
        marketSpec?: T;
        id?: T;
      };
  applications?: T;
  useCases?:
    | T
    | {
        text?: T;
        id?: T;
      };
  packSizes?:
    | T
    | {
        size?: T;
        catalogNumber?: T;
        grade?: T;
        id?: T;
      };
  leadTime?: T;
  bulkAvailable?: T;
  documents?: T;
  relatedProducts?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  generateSlug?: T;
  slug?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  shortName?: T;
  tagline?: T;
  description?: T;
  icon?: T;
  order?: T;
  image?: T;
  mode?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  summary?: T;
  description?: T;
  image?: T;
  workflows?:
    | T
    | {
        text?: T;
        id?: T;
      };
  recommendedProducts?: T;
  order?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  tagline?: T;
  summary?: T;
  description?: T;
  image?: T;
  deliverables?:
    | T
    | {
        text?: T;
        id?: T;
      };
  idealFor?:
    | T
    | {
        text?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        style?: T;
        eyebrow?: T;
        heading?: T;
        highlight?: T;
        text?: T;
        image?: T;
        imageMarker?: T;
        imageMarkerNote?: T;
        imageCaption?: T;
        imageCaptionNote?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        badges?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  layout?:
    | T
    | {
        richText?:
          | T
          | {
              content?: T;
              width?: T;
              id?: T;
              blockName?: T;
            };
        trustStrip?:
          | T
          | {
              source?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    value?: T;
                    unit?: T;
                    label?: T;
                    note?: T;
                    id?: T;
                  };
              style?: T;
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              columns?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    text?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                        };
                    id?: T;
                  };
              numbered?: T;
              id?: T;
              blockName?: T;
            };
        twoColumn?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              content?: T;
              links?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                          appearance?: T;
                        };
                    id?: T;
                  };
              image?: T;
              imageCaption?: T;
              imageCaptionNote?: T;
              imagePosition?: T;
              secondImage?: T;
              secondImageText?: T;
              quote?: T;
              background?: T;
              facts?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        comparisonTable?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              columnA?: T;
              columnB?: T;
              rows?:
                | T
                | {
                    parameter?: T;
                    a?: T;
                    b?: T;
                    id?: T;
                  };
              note?: T;
              id?: T;
              blockName?: T;
            };
        gradesPlatform?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              grades?:
                | T
                | {
                    name?: T;
                    badge?: T;
                    d50?: T;
                    sizeRange?: T;
                    maxFlow?: T;
                    pressure?: T;
                    text?: T;
                    id?: T;
                  };
              note?: T;
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
              blockName?: T;
            };
        resinSelector?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              id?: T;
              blockName?: T;
            };
        productCategories?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              categories?: T;
              footnote?: T;
              linkLabel?: T;
              id?: T;
              blockName?: T;
            };
        featuredProducts?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              products?: T;
              id?: T;
              blockName?: T;
            };
        applicationsGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
        servicesGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
        documentList?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              types?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        latestPosts?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        linkedInFeed?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              limit?: T;
              kind?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        teamGrid?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              members?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              items?:
                | T
                | {
                    date?: T;
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faqBlock?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              intro?: T;
              category?: T;
              faqs?: T;
              id?: T;
              blockName?: T;
            };
        mediaBlock?:
          | T
          | {
              image?: T;
              caption?: T;
              size?: T;
              id?: T;
              blockName?: T;
            };
        formBlock?:
          | T
          | {
              form?: T;
              heading?: T;
              intro?: T;
              sidebar?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              text?: T;
              note?: T;
              links?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                          appearance?: T;
                        };
                    id?: T;
                  };
              style?: T;
              id?: T;
              blockName?: T;
            };
        logoWall?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              source?: T;
              customers?: T;
              fallbackStatement?: T;
              id?: T;
              blockName?: T;
            };
        certificationsStrip?:
          | T
          | {
              heading?: T;
              kinds?: T;
              limit?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              items?:
                | T
                | {
                    image?: T;
                    label?: T;
                    caption?: T;
                    id?: T;
                  };
              layout?: T;
              id?: T;
              blockName?: T;
            };
        publications?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              member?: T;
              id?: T;
              blockName?: T;
            };
        proofBar?:
          | T
          | {
              showStatement?: T;
              style?: T;
              id?: T;
              blockName?: T;
            };
      };
  generateSlug?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  excerpt?: T;
  heroImage?: T;
  content?: T;
  tags?: T;
  relatedProducts?: T;
  author?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "updates_select".
 */
export interface UpdatesSelect<T extends boolean = true> {
  title?: T;
  url?: T;
  urn?: T;
  summary?: T;
  image?: T;
  relatedProducts?: T;
  kind?: T;
  publishedAt?: T;
  pinned?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  documentDate?: T;
  revision?: T;
  summary?: T;
  products?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  products?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  tagline?: T;
  bio?: T;
  photo?: T;
  credentials?:
    | T
    | {
        text?: T;
        id?: T;
      };
  expertise?:
    | T
    | {
        text?: T;
        id?: T;
      };
  publications?:
    | T
    | {
        title?: T;
        journal?: T;
        year?: T;
        url?: T;
        id?: T;
      };
  linkedinUrl?: T;
  email?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  person?: T;
  role?: T;
  organization?: T;
  country?: T;
  context?: T;
  logo?: T;
  products?: T;
  consentOnFile?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  name?: T;
  kind?: T;
  issuer?: T;
  statement?: T;
  validUntil?: T;
  document?: T;
  logo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  subjectLine?: T;
  type?: T;
  status?: T;
  name?: T;
  email?: T;
  organization?: T;
  jobTitle?: T;
  phone?: T;
  country?: T;
  items?:
    | T
    | {
        product?: T;
        productName?: T;
        grade?: T;
        packSize?: T;
        catalogNumber?: T;
        quantity?: T;
        purpose?: T;
        notes?: T;
        id?: T;
      };
  products?: T;
  requestedItems?: T;
  application?: T;
  message?: T;
  meta?:
    | T
    | {
        source?: T;
        pageUrl?: T;
        userAgent?: T;
        ip?: T;
        consent?: T;
      };
  internalNotes?: T;
  assignedTo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  organization?: T;
  status?: T;
  token?: T;
  confirmedAt?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  website?: T;
  sector?: T;
  country?: T;
  anonymisedLabel?: T;
  showLogo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  name: string;
  legalName?: string | null;
  tagline?: string | null;
  /**
   * One paragraph about the company. Used as the default meta description and given to AI assistants.
   */
  description?: string | null;
  foundedYear?: number | null;
  logo?: (number | null) | Media;
  /**
   * Variant for dark backgrounds (optional).
   */
  logoDark?: (number | null) | Media;
  /**
   * Short claims for the trust strip under the hero. Detailed certifications with issuer and certificate PDF live under Company → Certifications & claims.
   */
  certifications?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Facts about the company shown in the proof bar and given to AI assistants and search engines. Leave a field empty to hide it.
   */
  proof?: {
    /**
     * e.g. Founded May 2023
     */
    foundedText?: string | null;
    /**
     * e.g. 8–10 person team
     */
    teamSize?: string | null;
    /**
     * e.g. 600 L / month
     */
    capacity?: string | null;
    /**
     * One or two sentences about who uses Protpure resins. Shown where customer logos would go until logos can be published.
     */
    customersStatement?: string | null;
    /**
     * Optional. Update occasionally; shown next to the LinkedIn link.
     */
    linkedinFollowers?: number | null;
  };
  /**
   * Public contact email.
   */
  email?: string | null;
  phone?: string | null;
  /**
   * International format without spaces, e.g. +919426596644. Leave empty to hide the WhatsApp button.
   */
  whatsapp?: string | null;
  address?: string | null;
  city?: string | null;
  region?: string | null;
  country?: string | null;
  mapUrl?: string | null;
  /**
   * e.g. Mon–Sat, 9:30–18:00 IST
   */
  hours?: string | null;
  social?: {
    linkedin?: string | null;
    youtube?: string | null;
    x?: string | null;
  };
  /**
   * Every new quote/contact request is sent to these addresses.
   */
  notificationEmails?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Sender name for automated emails.
   */
  fromName?: string | null;
  /**
   * Reply-to address for automated emails.
   */
  replyTo?: string | null;
  /**
   * Promised response time shown on forms and in confirmation emails.
   */
  responseTime?: string | null;
  /**
   * Default lead time claim.
   */
  leadTime?: string | null;
  /**
   * Short statement about international supply, e.g. shipping, Incoterms, documentation.
   */
  globalStatement?: string | null;
  regions?:
    | {
        name: string;
        status?: ('direct' | 'distributor' | 'seeking') | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  exportNotes?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  titleSuffix?: string | null;
  ogImage?: (number | null) | Media;
  announcement?: {
    enabled?: boolean | null;
    text?: string | null;
    link?: {
      type?: ('internal' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: number | Page;
          } | null)
        | ({
            relationTo: 'products';
            value: number | Product;
          } | null)
        | ({
            relationTo: 'product-categories';
            value: number | ProductCategory;
          } | null)
        | ({
            relationTo: 'applications';
            value: number | Application;
          } | null)
        | ({
            relationTo: 'posts';
            value: number | Post;
          } | null);
      url?: string | null;
      label?: string | null;
    };
  };
  /**
   * Plausible domain or GA4 measurement ID (optional).
   */
  analyticsId?: string | null;
  /**
   * Plain-language paragraph served at /llms.txt describing what Protpure offers and how to buy.
   */
  aiSummary?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  /**
   * Short descriptor beside the logo, e.g. "Chromatography resins · Made in Anand, India". Use " · " to break lines.
   */
  tagline?: string | null;
  items?:
    | {
        link: {
          type?: ('internal' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'products';
                value: number | Product;
              } | null)
            | ({
                relationTo: 'product-categories';
                value: number | ProductCategory;
              } | null)
            | ({
                relationTo: 'applications';
                value: number | Application;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        children?:
          | {
              link: {
                type?: ('internal' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'products';
                      value: number | Product;
                    } | null)
                  | ({
                      relationTo: 'product-categories';
                      value: number | ProductCategory;
                    } | null)
                  | ({
                      relationTo: 'applications';
                      value: number | Application;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: number | Post;
                    } | null);
                url?: string | null;
                label: string;
              };
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    link?: {
      type?: ('internal' | 'custom') | null;
      newTab?: boolean | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: number | Page;
          } | null)
        | ({
            relationTo: 'products';
            value: number | Product;
          } | null)
        | ({
            relationTo: 'product-categories';
            value: number | ProductCategory;
          } | null)
        | ({
            relationTo: 'applications';
            value: number | Application;
          } | null)
        | ({
            relationTo: 'posts';
            value: number | Post;
          } | null);
      url?: string | null;
      label?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Short text under the logo.
   */
  tagline?: string | null;
  columns?:
    | {
        title: string;
        links?:
          | {
              link: {
                type?: ('internal' | 'custom') | null;
                newTab?: boolean | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'products';
                      value: number | Product;
                    } | null)
                  | ({
                      relationTo: 'product-categories';
                      value: number | ProductCategory;
                    } | null)
                  | ({
                      relationTo: 'applications';
                      value: number | Application;
                    } | null)
                  | ({
                      relationTo: 'posts';
                      value: number | Post;
                    } | null);
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  newsletter?: {
    heading?: string | null;
    /**
     * Label above the email field.
     */
    text?: string | null;
    /**
     * Consent line under the field.
     */
    note?: string | null;
  };
  legalLinks?:
    | {
        link: {
          type?: ('internal' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'products';
                value: number | Product;
              } | null)
            | ({
                relationTo: 'product-categories';
                value: number | ProductCategory;
              } | null)
            | ({
                relationTo: 'applications';
                value: number | Application;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. Registered in India · CIN …
   */
  bottomText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  legalName?: T;
  tagline?: T;
  description?: T;
  foundedYear?: T;
  logo?: T;
  logoDark?: T;
  certifications?:
    | T
    | {
        text?: T;
        id?: T;
      };
  proof?:
    | T
    | {
        foundedText?: T;
        teamSize?: T;
        capacity?: T;
        customersStatement?: T;
        linkedinFollowers?: T;
      };
  email?: T;
  phone?: T;
  whatsapp?: T;
  address?: T;
  city?: T;
  region?: T;
  country?: T;
  mapUrl?: T;
  hours?: T;
  social?:
    | T
    | {
        linkedin?: T;
        youtube?: T;
        x?: T;
      };
  notificationEmails?:
    | T
    | {
        email?: T;
        id?: T;
      };
  fromName?: T;
  replyTo?: T;
  responseTime?: T;
  leadTime?: T;
  globalStatement?: T;
  regions?:
    | T
    | {
        name?: T;
        status?: T;
        note?: T;
        id?: T;
      };
  exportNotes?:
    | T
    | {
        text?: T;
        id?: T;
      };
  titleSuffix?: T;
  ogImage?: T;
  announcement?:
    | T
    | {
        enabled?: T;
        text?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
      };
  analyticsId?: T;
  aiSummary?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  tagline?: T;
  items?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        children?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              description?: T;
              id?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tagline?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  newsletter?:
    | T
    | {
        heading?: T;
        text?: T;
        note?: T;
      };
  legalLinks?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  bottomText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}